'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, BookOpen, Check, ChevronLeft, ChevronRight, Home, RotateCcw, Target } from 'lucide-react'
import { examLabels, modeLabels, type ExamType, type StudyMode } from '@/lib/exams/types'
import { traditionalContent } from '@/lib/exams/traditional'
import { vulContent } from '@/lib/exams/vul'

type Screen = 'dashboard' | 'progress' | 'flashcard' | 'memorize' | 'practice'
const content = (type: ExamType) => type === 'vul' ? vulContent : traditionalContent

function ProgressBar({ value, blue = false }: { value: number; blue?: boolean }) {
  return <div className="h-2.5 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${blue ? 'bg-primary' : 'bg-emerald-500'}`} style={{ width: `${value}%` }} /></div>
}
function Card({ children }: { children: React.ReactNode }) { return <section className="rounded-3xl border border-border bg-card p-5 shadow-sm">{children}</section> }
function Header({ home, progress }: { home: () => void; progress: () => void }) { return <header className="flex items-center justify-between px-5 py-5"><button onClick={home} className="flex items-center gap-2 font-mono text-sm font-bold"><span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><BookOpen className="size-4" /></span> REVIEWER</button><button onClick={progress} className="rounded-full p-2 text-muted-foreground hover:bg-muted" aria-label="View progress"><BarChart3 className="size-5" /></button></header> }

function Dashboard({ select }: { select: (mode: StudyMode) => void }) { return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><div className="pt-3"><p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Insurance licensing</p><h1 className="mt-2 text-3xl font-bold">Your Reviewer</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose a study mode and keep moving toward exam day.</p></div><Card><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Reviewer</h2><Target className="size-5 text-primary" /></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted p-4"><p className="font-mono text-xs uppercase text-muted-foreground">VUL</p><p className="mt-2 text-2xl font-bold">68%</p><ProgressBar value={68} /></div><div className="rounded-2xl bg-muted p-4"><p className="font-mono text-xs uppercase text-muted-foreground">Traditional</p><p className="mt-2 text-2xl font-bold">42%</p><ProgressBar value={42} blue /></div></div></Card><Card><div className="flex flex-col gap-3">{(['flashcard', 'memorize', 'practice'] as StudyMode[]).map((mode) => <button key={mode} onClick={() => select(mode)} className="flex items-center justify-between rounded-2xl border border-border px-4 py-4 text-left font-semibold hover:border-primary"><span className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-muted">{mode === 'flashcard' ? <BookOpen className="size-4" /> : mode === 'memorize' ? <RotateCcw className="size-4" /> : <Target className="size-4" />}</span>{modeLabels[mode]}</span><ArrowRight className="size-4 text-muted-foreground" /></button>)}</div></Card></main> }
function Picker({ mode, choose, back }: { mode: StudyMode; choose: (type: ExamType) => void; back: () => void }) { return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={back} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><div><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">{modeLabels[mode]}</p><h1 className="mt-2 text-3xl font-bold">What are you studying?</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose the exam content you want to review.</p></div>{(['vul', 'traditional'] as ExamType[]).map((type) => <button key={type} onClick={() => choose(type)} className="rounded-3xl border border-border bg-card p-5 text-left shadow-sm hover:border-primary"><div className="flex items-center justify-between"><div><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Exam type</p><h2 className="mt-2 text-2xl font-bold">{examLabels[type]}</h2></div><ArrowRight className="text-muted-foreground" /></div><div className="mt-5"><ProgressBar value={type === 'vul' ? 68 : 42} blue={type === 'traditional'} /></div></button>)}</main> }
function Study({ mode, type, back }: { mode: 'flashcard' | 'memorize'; type: ExamType; back: () => void }) { const questions = content(type).questions; const [index, setIndex] = useState(0); const question = questions[index]; return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={back} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><div className="flex items-center justify-between"><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">{examLabels[type]} · {modeLabels[mode]}</p><span className="text-xs text-muted-foreground">{index + 1} / {questions.length}</span></div><ProgressBar value={((index + 1) / questions.length) * 100} /><Card><p className="font-mono text-xs uppercase text-primary">{question.section}</p><h1 className="mt-6 text-xl font-semibold leading-8">{question.prompt}</h1>{mode === 'memorize' && <p className="mt-8 rounded-2xl bg-muted p-4 text-sm leading-6 text-muted-foreground">Think through the answer before revealing it.</p>}</Card><div className="flex justify-between"><button onClick={() => setIndex((index - 1 + questions.length) % questions.length)} className="rounded-xl border border-border p-3" aria-label="Previous"><ChevronLeft className="size-5" /></button><button onClick={() => setIndex((index + 1) % questions.length)} className="flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Next <ChevronRight className="size-4" /></button></div></main> }
function Practice({ type, back }: { type: ExamType; back: () => void }) { const questions = content(type).questions; const [index, setIndex] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [submitted, setSubmitted] = useState(false); const q = questions[index]; const next = () => { if (index < questions.length - 1) { setIndex(index + 1); setSelected(null); setSubmitted(false) } else back() }; return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={back} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><div><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">{examLabels[type]} · Practice Exam</p><h1 className="mt-2 text-2xl font-bold">Question {index + 1} of {questions.length}</h1></div><ProgressBar value={((index + (submitted ? 1 : 0)) / questions.length) * 100} /><Card><p className="font-mono text-xs uppercase text-primary">{q.section}</p><h2 className="mt-5 text-lg font-semibold leading-7">{q.prompt}</h2><div className="mt-6 flex flex-col gap-3">{q.answers.map((answer) => <button key={answer.id} onClick={() => !submitted && setSelected(answer.id)} className={`rounded-2xl border p-4 text-left text-sm ${selected === answer.id && !submitted ? 'border-primary bg-primary/10' : submitted && answer.correct ? 'border-emerald-500 bg-emerald-50' : 'border-border hover:border-primary'}`}><span className="mr-3 font-mono text-xs uppercase text-muted-foreground">{answer.id}</span>{answer.text}{submitted && answer.correct && <Check className="float-right size-4 text-emerald-600" />}</button>)}</div>{submitted && <p className="mt-5 rounded-2xl bg-muted p-4 text-sm leading-6">{q.explanation}</p>}</Card>{!submitted ? <button disabled={!selected} onClick={() => setSubmitted(true)} className="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50">Check answer</button> : <button onClick={next} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">{index === questions.length - 1 ? 'Finish' : 'Next question'} <ChevronRight className="size-4" /></button>}</main> }
function Progress({ back }: { back: () => void }) { return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={back} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><h1 className="text-3xl font-bold">My Progress</h1><Card><p className="text-sm text-muted-foreground">Overall progress</p><p className="mt-1 text-4xl font-bold">55%</p><div className="mt-5"><ProgressBar value={55} /></div></Card><Card><h2 className="font-bold">Exam progress</h2><div className="mt-5 flex flex-col gap-5"><div><div className="mb-2 flex justify-between text-sm"><span>VUL</span><strong>68%</strong></div><ProgressBar value={68} /></div><div><div className="mb-2 flex justify-between text-sm"><span>Traditional</span><strong>42%</strong></div><ProgressBar value={42} blue /></div></div></Card></main> }
export default function Page() { const [screen, setScreen] = useState<Screen>('dashboard'); const [mode, setMode] = useState<StudyMode | null>(null); const [type, setType] = useState<ExamType | null>(null); const select = (next: StudyMode) => { setMode(next); setType(null); setScreen('dashboard') }; const choose = (next: ExamType) => { setType(next); setScreen(mode ?? 'dashboard') }; const home = () => { setMode(null); setType(null); setScreen('dashboard') }; const back = () => { setMode(null); setType(null); setScreen('dashboard') }; return <div className="min-h-screen bg-background text-foreground"><Header home={home} progress={() => { setMode(null); setType(null); setScreen('progress') }} />{screen === 'dashboard' && !mode && <Dashboard select={select} />}{screen === 'dashboard' && mode && !type && <Picker mode={mode} choose={choose} back={back} />}{type && (screen === 'flashcard' || screen === 'memorize') && <Study mode={screen} type={type} back={back} />}{type && screen === 'practice' && <Practice type={type} back={back} />}{screen === 'progress' && <Progress back={home} />}<footer className="mx-auto flex max-w-2xl justify-center px-5 pb-8"><button onClick={home} className="flex items-center gap-2 text-xs text-muted-foreground"><Home className="size-3.5" /> Reviewer home</button></footer></div> }
