'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, BookOpen, Check, ChevronLeft, ChevronRight, Clock3, Home, RotateCcw, Target } from 'lucide-react'
import { examLabels, getExamContent, modeLabels, type ExamType, type StudyMode } from '@/lib/exams/types'
import { traditionalContent } from '@/lib/exams/traditional'
import { vulContent } from '@/lib/exams/vul'

type Screen = 'dashboard' | 'progress' | 'flashcard' | 'memorize' | 'practice'

function ProgressBar({ value, color = 'green' }: { value: number; color?: 'green' | 'blue' }) { return <div className="h-2.5 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${color === 'blue' ? 'bg-primary' : 'bg-emerald-500'}`} style={{ width: `${value}%` }} /></div> }
function Header({ onHome, onProgress }: { onHome: () => void; onProgress: () => void }) { return <header className="flex items-center justify-between px-5 py-5"><button onClick={onHome} className="flex items-center gap-2 font-mono text-sm font-bold tracking-tight text-foreground"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><BookOpen className="size-4" /></span> REVIEWER</button><button onClick={onProgress} className="rounded-full p-2 text-muted-foreground hover:bg-muted" aria-label="View progress"><BarChart3 className="size-5" /></button></header> }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-3xl border border-border bg-card p-5 shadow-sm ${className}`}>{children}</section> }

function Dashboard({ select }: { select: (mode: StudyMode) => void }) { return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><div className="pt-3"><p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Insurance licensing</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Your Reviewer</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose a study mode and keep moving toward exam day.</p></div><Card><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Your progress</h2><Target className="size-5 text-primary" /></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted p-4"><p className="font-mono text-xs uppercase text-muted-foreground">VUL</p><p className="mt-2 text-2xl font-bold">68%</p><ProgressBar value={68} /></div><div className="rounded-2xl bg-muted p-4"><p className="font-mono text-xs uppercase text-muted-foreground">Traditional</p><p className="mt-2 text-2xl font-bold">42%</p><ProgressBar value={42} color="blue" /></div></div></Card><Card><div className="flex flex-col gap-3">{([['flashcard', BookOpen], ['memorize', RotateCcw], ['practice', Target]] as const).map(([mode, Icon]) => <button key={mode} onClick={() => select(mode)} className="flex items-center justify-between rounded-2xl border border-border px-4 py-4 text-left font-semibold transition hover:border-primary"><span className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-muted"><Icon className="size-4" /></span>{modeLabels[mode]}</span><ArrowRight className="size-4 text-muted-foreground" /></button>)}</div></Card></main> }

function ExamPicker({ mode, choose, cancel }: { mode: StudyMode; choose: (type: ExamType) => void; cancel: () => void }) { return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={cancel} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground">{modeLabels[mode]}</p><h1 className="mt-2 text-3xl font-bold">What are you studying?</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose the exam content you want to review.</p></div><div className="flex flex-col gap-4">{(['vul', 'traditional'] as ExamType[]).map((type) => <button key={type} onClick={() => choose(type)} className="rounded-3xl border border-border bg-card p-5 text-left shadow-sm transition hover:border-primary"><div className="flex items-center justify-between"><div><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Exam type</p><h2 className="mt-2 text-2xl font-bold">{examLabels[type]}</h2></div><ArrowRight className="text-muted-foreground" /></div><div className="mt-5"><ProgressBar value={type === 'vul' ? 68 : 42} color={type === 'vul' ? 'green' : 'blue'} /></div></button>)}</div></main> }

function StudyPage({ mode, type, go }: { mode: 'flashcard' | 'memorize'; type: ExamType; go: (screen: Screen) => void }) { const questions = getExamContent(type, type === 'vul' ? vulContent : traditionalContent); const [index, setIndex] = useState(0); const question = questions[index]; return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={() => go('dashboard')} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><div className="flex items-center justify-between"><p className="font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground">{examLabels[type]} · {modeLabels[mode]}</p><span className="text-xs text-muted-foreground">{index + 1} / {questions.length}</span></div><ProgressBar value={((index + 1) / questions.length) * 100} /><Card className="min-h-64"><p className="font-mono text-xs uppercase text-primary">{question.section}</p><h1 className="mt-6 text-xl font-semibold leading-8">{question.prompt}</h1>{mode === 'memorize' && <p className="mt-8 rounded-2xl bg-muted p-4 text-sm leading-6 text-muted-foreground">Think through the answer before revealing it. The correct answer is maintained in the selected exam content module.</p>}</Card><div className="flex items-center justify-between"><button onClick={() => setIndex((index - 1 + questions.length) % questions.length)} className="rounded-xl border border-border p-3" aria-label="Previous"><ChevronLeft className="size-5" /></button><button onClick={() => setIndex((index + 1) % questions.length)} className="flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Next <ChevronRight className="size-4" /></button></div></main> }

function Practice({ type, go }: { type: ExamType; go: (screen: Screen) => void }) { const questions = getExamContent(type, type === 'vul' ? vulContent : traditionalContent); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [submitted, setSubmitted] = useState(false); const question = questions[index]; const next = () => { if (index < questions.length - 1) { setIndex(index + 1); setSelected(null); setSubmitted(false) } else go('progress') }; return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={() => go('dashboard')} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><div className="flex items-center justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground">{examLabels[type]} · Practice Exam</p><h1 className="mt-2 text-2xl font-bold">Question {index + 1} of {questions.length}</h1></div><Clock3 className="size-5 text-muted-foreground" /></div><ProgressBar value={((index + (submitted ? 1 : 0)) / questions.length) * 100} /><Card><p className="font-mono text-xs uppercase text-primary">{question.section}</p><h2 className="mt-5 text-lg font-semibold leading-7">{question.prompt}</h2><div className="mt-6 flex flex-col gap-3">{question.answers.map((answer) => <button key={answer.id} onClick={() => !submitted && setSelected(answer.id)} className={`rounded-2xl border p-4 text-left text-sm font-medium transition ${selected === answer.id && !submitted ? 'border-primary bg-primary/10' : submitted && answer.correct ? 'border-emerald-500 bg-emerald-50' : submitted && selected === answer.id ? 'border-destructive bg-destructive/10' : 'border-border hover:border-primary'}`}><span className="mr-3 font-mono text-xs uppercase text-muted-foreground">{answer.id}</span>{answer.text}{submitted && answer.correct && <Check className="float-right size-4 text-emerald-600" />}</button>)}</div>{submitted && <p className="mt-5 rounded-2xl bg-muted p-4 text-sm leading-6 text-muted-foreground">{question.explanation}</p>}</Card>{!submitted ? <button disabled={!selected} onClick={() => setSubmitted(true)} className="rounded-2xl bg-primary px-5 py-4 text-sm font-bold text-primary-foreground disabled:opacity-40">Check answer</button> : <button onClick={next} className="rounded-2xl bg-primary px-5 py-4 text-sm font-bold text-primary-foreground">{index === questions.length - 1 ? 'Finish exam' : 'Next question'}</button>}</main> }

function Progress({ go }: { go: (screen: Screen) => void }) { return <main className="mx-auto flex w-full max-w-2xl flex-col gap-5 px-5 pb-10"><button onClick={() => go('dashboard')} className="flex items-center gap-1 self-start text-sm text-muted-foreground"><ChevronLeft className="size-4" /> Back</button><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground">My Progress</p><h1 className="mt-2 text-3xl font-bold">Keep going.</h1></div><Card><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Overall progress</p><p className="mt-1 text-4xl font-bold">55%</p></div><BarChart3 className="size-7 text-primary" /></div><div className="mt-5"><ProgressBar value={55} /></div></Card><Card><h2 className="font-bold">Exam progress</h2><div className="mt-5 flex flex-col gap-5"><div><div className="mb-2 flex justify-between text-sm"><span>VUL</span><strong>68%</strong></div><ProgressBar value={68} /></div><div><div className="mb-2 flex justify-between text-sm"><span>Traditional</span><strong>42%</strong></div><ProgressBar value={42} color="blue" /></div></div></Card></main> }

export default function Page() { const [screen, setScreen] = useState<Screen>('dashboard'); const [mode, setMode] = useState<StudyMode | null>(null); const [examType, setExamType] = useState<ExamType | null>(null); const go = (next: Screen) => setScreen(next); const selectMode = (nextMode: StudyMode) => { setMode(nextMode); setExamType(null) }; const chooseExam = (type: ExamType) => { setExamType(type); setScreen(mode as Screen) }; return <div className="min-h-screen bg-background text-foreground"><Header onHome={() => go('dashboard')} onProgress={() => go('progress')} />{screen === 'dashboard' && !mode && <Dashboard select={selectMode} />}{screen === 'progress' && <Progress go={go} />}{mode && !examType && screen === 'dashboard' && <ExamPicker mode={mode} choose={chooseExam} cancel={() => setMode(null)} />}{mode && !examType && screen !== 'dashboard' && <ExamPicker mode={mode} choose={chooseExam} cancel={() => go('dashboard')} />}{examType && (screen === 'flashcard' || screen === 'memorize') && <StudyPage mode={screen} type={examType} go={go} />}{examType && screen === 'practice' && <Practice type={examType} go={go} />}<footer className="mx-auto flex max-w-2xl justify-center px-5 pb-8"><button onClick={() => go('dashboard')} className="flex items-center gap-2 text-xs text-muted-foreground"><Home className="size-3.5" /> Reviewer home</button></footer></div> }
